### ISSUE TITLE
Question: Does it work with crash from 3th party C/C++ libs?

### ISSUE THREAD

**Issue by amadeu01** [MindorksOpenSource/CrashReporter#4]
I have one library on my project that crashes with some native code in C/C++ like segmentation fault.

That exception does not come to my Java code (It is not passed forward from the native code to the Java code)

So, my question is, does this library work on getting thoses kind of crashes ?

Thanks in advance!

**Comment by balsikandar** [comment]
Sorry for late response and no it doesn't works for that.
