### ISSUE TITLE
failed to post notification on channel null android

### ISSUE THREAD

**Issue by monsterbrain** [MindorksOpenSource/CrashReporter#6]
I've integrated the library. On Checking crash with emulator v api 27, the notification is not appearing. Just showing a toast

Developer warning for package "mypackage.appname" failed to post notification on channel null

Please update .

**Comment by balsikandar** [comment]
Thanks will update over this weekend and will let you know. Thanks

**Comment by monsterbrain** [comment]
I think it's due to the new oreo notification system, where a channel is required for notifications I guess ...
